# Generated by Django 4.2.11 on 2026-03-22 15:38

import bookings.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_ref', models.CharField(db_index=True, default=bookings.models.generate_booking_ref, max_length=30, unique=True)),
                ('visitor_name', models.CharField(max_length=200)),
                ('visitor_email', models.EmailField(max_length=254)),
                ('visitor_phone', models.CharField(max_length=20)),
                ('quantity_adult', models.PositiveIntegerField(default=1)),
                ('quantity_child', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('dialogflow_session', models.CharField(blank=True, db_index=True, max_length=200)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='shows.show')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
