# Generated by Django 4.2.11 on 2026-03-22 15:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('general', 'General Entry'), ('exhibition', 'Exhibition'), ('night_show', 'Night Show'), ('special', 'Special Show')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_capacity', models.PositiveIntegerField()),
                ('booked_count', models.PositiveIntegerField(default=0)),
                ('price_adult', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_child', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Show',
                'db_table': 'shows',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
